### ISSUE TITLE
ILPSolverError: Potential Graph could not be found with solver parameters. 

### ISSUE THREAD

**Issue by tenlives** [YosefLab/Cassiopeia#239] opened 2024-03-13 08:50 UTC
Hi, thanks for the great tool. When I try to use the command below,

'ilp_solver = cas.solver.ILPSolver(convergence_time_limit=500, maximum_potential_graph_layer_size=500, weighted=True, seed=1234)
ilp_solver.solve(cas_tree)'

I got this error message 'ILPSolverError: Potential Graph could not be found with solver parameters. Try increasing `maximum_potential_graph_layer_size` or using another solver.'

Although I increase the maximum_potential_graph_layer_size, it still doesn`t work.
I tried the demo data 'GSM4905334_alleleTable.5k.txt.gz', it works.
So could you provide me much information about why my dataset not suitable to this method?

**Comment by mattjones315** [comment] 2024-03-13 16:14
Hello,

Thanks for your issue and using Cassiopeia. The parameters used in the
tutorial are not realistic for real datasets, and are set to those low
values just so the tool can run quickly in a tutorial environment. Instead
we recommend using much higher parameters - please see text above in the
tutorial, reproduced here:

``There are several parameters of interest which can all be explored
on our documentation
website
<https://cassiopeia-lineage.readthedocs.io/en/latest/api/reference/cassiopeia.solver.ILPSolver.html#cassiopeia.solver.ILPSolver>.
Because this process can take a long time, we’ll restrict the potential
graph layer size to 500 nodes and the convergence time to 500s. A more
realistic solver might use our defaults - namely, a maximum potential graph
layer size of 10,000 and a convergence time of 12,600s (3.5hr).``

Can you let me know if you tried these parameters and it still did not work?

Thanks,
Matt

**Comment by mattjones315** [comment] 2024-03-13 17:09
Hi @tenlives, you can try bootstrapping (we have functionality for creating bootstrapped character matrices), but perhaps easier to evaluate parsimony of the trees to select the best tree. This is what we have done in the past.

Another recommendation is to evaluate downstream analyses on all four trees to see how robust downstream conclusions are.

If it's alright, I'll close this issue unless you run into any problems again with the ILPSolver.

**Closed by mattjones315** 2024-03-13 17:09 UTC

**Comment by tenlives** [comment] 2024-03-13 17:23
very clear， thanks very much
